@startuml
class com.zenika.zacademy.Main {
+ {static} void main(String[])
}
abstract class com.zenika.zacademy.Person {
+ String firstName
+ String lastName
+ String phoneNumber
+ String address
+ String email
+ boolean equals(Object)
+ int hashCode()
}
class com.zenika.zacademy.Student {
+ String toString()
}
class com.zenika.zacademy.PromotionNotFoundException {
}
class com.zenika.zacademy.display.CheckNorrisDisplay {
+ void print(String)
}
class com.zenika.zacademy.Former {
+ String toString()
}
interface com.zenika.zacademy.display.Display {
~ void print(String)
}
class com.zenika.zacademy.Directory {
- Set<Promotion> promotions
- Set<Person> persons
+ Set<Person> getPersons()
+ Set<Promotion> getPromotions()
+ void addUniquePerson(Person)
+ Optional<Person> searchPersonByName(String)
+ Promotion searchPromotionById(int)
}
class com.zenika.zacademy.Promotion {
- int id
- String name
- Set<Former> formers
- Set<Student> students
+ int getId()
+ Set<Former> getFormers()
+ Set<Student> getStudents()
+ String toString()
}
class com.zenika.zacademy.display.TerminalDisplay {
+ void print(String)
}


com.zenika.zacademy.Person <|-- com.zenika.zacademy.Student
com.zenika.zacademy.Exception <|-- com.zenika.zacademy.PromotionNotFoundException
com.zenika.zacademy.display.Display <|.. com.zenika.zacademy.display.CheckNorrisDisplay
com.zenika.zacademy.Person <|-- com.zenika.zacademy.Former
com.zenika.zacademy.display.Display <|.. com.zenika.zacademy.display.TerminalDisplay
@enduml